version: "2"

run:
  timeout: 10m
  tests: true
  allow-parallel-runners: true
  go: "1.25"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - misspell
    - unparam
    - prealloc
    # - gosec
    - noctx
  settings:
    misspell:
      locale: US

formatters:
  enable:
    - gofmt
    - goimports
